# Generated by Django 5.0.6 on 2024-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quiz_answer_quiz_description_quiz_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
