# Generated by Django 5.0.6 on 2024-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_quiz_answer_userquiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
