# Generated by Django 5.0.6 on 2024-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_quiz_description_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
