# Generated by Django 5.0.6 on 2024-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_quiz_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='status',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
