# Generated by Django 5.0.6 on 2024-12-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userquiz_comment_alter_userquiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
