# Generated by Django 5.0.6 on 2024-12-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='answer',
        ),
    ]
