# Generated by Django 5.0.6 on 2024-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_userquiz_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
